### ISSUE TITLE
Hashable instances for Vector types

### ISSUE THREAD

**Issue by phadej** [tibbe/hashable#108]
There are three options:
- Add instance into `hashable`
- Add instances into `vector`
- Add instances into new `vector-hashable`

As `hashable` already depends on `text`, it could depend on `vector` as well. So I'd go with first option if it's ok with the maintainers of `hashable`. I'll make a PR if this is ok.

**Comment by tibbe** [comment]
After discussing this with some people in the past (e.g. @dcoutts) I think we concluded that type classes should be on the bottom of the dependency chain (i.e. vector should depend on hashable). That it works the other way around for text is a bit of an accident.

**Comment by phadej** [comment]
ok. I'll try to get the change into `vector` then. Thanks for quick response!
