### ISSUE TITLE
Add Hashable for Ptr/IntPtr/WordPtr

### ISSUE THREAD

**Issue by ndmitchell** [tibbe/hashable#119]
All these types are basically Int's, so could have Hashable instances. I am thinking of just hashing the pointer, not the memory pointed at by the pointer, which is the only sensible instance. As a temporary hack I'm using:

    hashWithSalt salt $ toInteger $ ptrToIntPtr p

**Comment by tibbe** [comment]
Sounds reasonable. Want to whip up a PR?
