### ISSUE TITLE
Hashed NFData instance

### ISSUE THREAD

**Issue by minad** [tibbe/hashable#130]
Could we add such an instance here?

**Comment by phadej** [comment]
Seems reasonable. `deepseq` is a boot package, so there isn't any problem depending on it.

I'm not a maintainer, but I hope tibbe will accept the PR if you make one. `hashable` works with GHC7.4+, so you have to support `deepseq >= 1.3`, i.e. write the instance manually. https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory

**Comment by minad** [comment]
see #131
