### ISSUE TITLE
Tiny output range when deriving Hashable for Peano Nat type

### ISSUE THREAD

**Issue by Warbo** [tibbe/hashable#135]
Hello, I've got some code which defines the following very simple type for Peano natural numbers:

```
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveDataTypeable #-}
import Data.Typeable
import GHC.Generics
import Data.Hashable
data Nat = Z | S Nat deriving (Generic, Eq, Ord, Show, Typeable)
instance Hashable Nat
```

The `Hashable` instance is created, and I can get hashes:

```
> Data.Hashable.hash Z
-1926854076
> Data.Hashable.hash (S Z)
-1943630889
```

However, it looks like these are the *only* two hashes that are ever generated (formatted to make the alternation clear):

```
> take 100 (map hash (iterate S Z))
[-1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889,
 -1926854076,-1943630889]
```

I expected that such a recursive type would lose some range, but this seems like very poor performance for such a simple and common example :(

This is running on 32bit Linux (NixOS) with GHC 7.10.3 and hashable 1.2.4.0. I see that 1.2.5.0 is on Hackage, so I'll retry with that.

**Comment by Warbo** [comment]
I've tried with 1.2.5.0 and get the same results :(

**Comment by tibbe** [comment]
That's bad. Unfortunately I didn't write the generics code so I'm not sure what's wrong (I also find GHC generics inscrutable). Perhaps someone like @andrewthad who has worked on that code could help.

**Comment by andrewthad** [comment]
When I last looked at the generics code, I noticed that something weird was going on with sum types. Here are the [two provided instances of GSum](https://github.com/tibbe/hashable/blob/77fd41a95e9fc74fc6d1ea53311b084d0f909215/Data/Hashable/Generic.hs) and the implementations of `hashSum`:

    instance (GSum arity a, GSum arity b) => GSum arity (a :+: b) where
        hashSum toHash !salt !code !size s = case s of
            L1 x -> hashSum toHash salt code           sizeL x
            R1 x -> hashSum toHash salt (code + sizeL) sizeR x
          where
            sizeL = size `shiftR` 1
            sizeR = size - sizeL
        {-# INLINE hashSum #-}

    instance GHashable arity a => GSum arity (C1 c a) where
        -- hashSum toHash !salt !code _ (M1 x) = ghashWithSalt toHash (hashWithSalt salt code) x
        hashSum toHash !salt !code _ (M1 x) = hashWithSalt salt (ghashWithSalt toHash code x)
        {-# INLINE hashSum #-}

These two work together as a form of type-level induction. The instance for `C1` is the base case and the instance for `:+:` in the induction step. But notice that in the base case, `hashSum` ignores its fourth argument, `size`. To me, it wasn't totally clear what `size` actually means. It looks like @phadej's PR cleans this up. I'll take a look and see if I can understand it any better than the previous implementation.
