### ISSUE TITLE
Expose gHashWithSalt?

### ISSUE THREAD

**Issue by jkarni** [tibbe/hashable#148]
Often a datatype that I want to be `Hashable` will contain fields that are not themselves `Hashable` (which in turn themselves may contain fields which are not `Hashable`), though they are all `Generic`. Writing an instance in that case could be considerably simplified if `gHashWithSalt` was exposed. Is there any reason not to?

**Comment by netom** [comment]
I second this. https://stackoverflow.com/questions/51100263

**Comment by hvr** [comment]
Resolved by #178
