### ISSUE TITLE
base constraint needs updating for ghc 8.4; anything else?

### ISSUE THREAD

**Issue by DougBurke** [tibbe/hashable#149]
I was able to get `hashable` to build with the recent ghc 8.4.0 alpha by upping the base constraint to 

```
  Build-depends:     base >= 4.4 && < 4.12,
```

which produced one warning:

```
[2 of 4] Compiling Data.Hashable.Generic ( Data/Hashable/Generic.hs, /home/djburke/swish/hashable-1.2.6.1/dist-newstyle/build/hashable-1.2.6.1/build/Data/Hashable/Generic.o )

Data/Hashable/Generic.hs:21:1: warning: [-Wunused-imports]
    The import of ‘Data.Bits’ is redundant
      except perhaps to import instances from ‘Data.Bits’
    To import instances alone, use: import Data.Bits()
   |
21 | import Data.Bits (shiftR)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is with

```
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.0.20171214
```

I didn't get to running the test suite since `primitive` also needs updating and I don't want to go too far down this particular rabbit hole at this time!

**Comment by phadej** [comment]
Based on lack of patch in https://github.com/hvr/head.hackage/tree/master/patches, most likely: *no*, no other changes needed atm.

**Comment by DougBurke** [comment]
Thanks for the link @phadej

**Comment by asr** [comment]
Before knowing this issue, I wrote the (trivial) PR #150 fixing it.

**Comment by kazu-yamamoto** [comment]
I think

```
Build-depends:     base >= 4.4 && < 5,
```

is better.

**Comment by hvr** [comment]
@kazu-yamamoto why? ;-)

**Comment by kazu-yamamoto** [comment]
If `hashable` is not depend `base` too much, I think it's wise to not loose version boundaries for every GHC.

**Comment by phadej** [comment]
@kazu-yamamoto  you could bring that to CLC to make `base` version semantics such that the super major version bound will be done if changes in `base` will break any Haskell Platform packages, which would meant that AMP/FTP (in `base-4.8`) and `SMP` (in `base-4.11`) would been `base-5` and `base-6` respectively. Then I as a maintainer of (other) package in Haskell Platform would be very happy to use super major upper bound like `base < 5`.

The `base <5` bound **doesn't have any agreed semantics** at the moment, so I personally won't use it myself and won't recommend to others.

**Comment by kazu-yamamoto** [comment]
@phadej Probably, I should use `--allow-newer` of cabal-install for my purpose. :-)

**Comment by hvr** [comment]
This can be considered resolved by  http://hackage.haskell.org/package/hashable-1.2.7.0

**Comment by kazu-yamamoto** [comment]
@hvr Big thank you!
