### ISSUE TITLE
Update `base` version on Hackage

### ISSUE THREAD

**Issue by ChShersh** [tibbe/hashable#167]
Is it possible to upload new version of `hashable` to Hackage with relaxed upper-bounds for `base` or at least use cabal revisions to do it?

**Comment by hvr** [comment]
Note that GHC 8.6 is still in alpha state and hasn't been released yet so it's a bit too early to advertise support for what's still a moving target.

**Comment by ChShersh** [comment]
@hvr Thanks a lot! Yes, you're right, probably it's too early. I'm using `--allow-newer` for now and it works fine :+1:

**Comment by hvr** [comment]
Done via http://hackage.haskell.org/package/hashable-1.2.7.0/revisions/
