### ISSUE TITLE
Can't import Data.Hashable

### ISSUE THREAD

**Issue by aliakbar32** [tibbe/hashable#170]
Already had hashable installed but can't import Data.Hashable
`
GHCi, version 8.4.3: http://www.haskell.org/ghc/  :? for help
Prelude> import Data.Hashable

<no location info>: error:
    Could not find module ‘Data.Hashable’
    Perhaps you haven't installed the "dyn" libraries for package ‘hashable-1.2.7.0’?
    Use -v to see a list of the files searched for.
`

**Comment by phadej** [comment]
@aliakbar32 are you on Arch Linux? Does https://wiki.archlinux.org/index.php/Haskell#Problems_with_linking light something to your issues?

**Comment by aliakbar32** [comment]
Yep I am on Arch Linux. Reinstalled hashable with those arguments. Everything works now. Thank you.
