### ISSUE TITLE
hashable instance for primarray?

### ISSUE THREAD

**Issue by chessai** [tibbe/hashable#174]
it would be basically the same as the instance for list.

```haskell
instance (Hashable a, Prim a) => Hashable (PrimArray a) where
  hashWithSalt s arr = finalise (foldlPrimArray' step (SP salt 0) arr)
    where
      finalise (SP s l) = hashWithSalt s l
      step (SP s l) x   = SP (hashWithSalt s x) (l + 1)
```

i've seen issue #108 about getting hashable instances for vector types here, but i'm not sure if that applies to primitive as well. let me know your thoughts

**Comment by hvr** [comment]
@chessai that would incur an additional dependency on `primitive` which has been successfully avoided so far and this would only make it more difficult to push `class Hashable` lower down the hierarchy closer to `base`.

**Comment by chessai** [comment]
Understood.
