### ISSUE TITLE
‘hashWithSalt’ is not a (visible) method of class ‘Hashable’

### ISSUE THREAD

**Issue by tycho01** [tibbe/hashable#181]
I am currently using `hashable` version `1.3.0.0`, and would like to define an instance on a class:
```
import Data.Hashable (Hashable)
data Foo = Foo
instance Hashable Foo where
    hashWithSalt = const
```
unfortunately, this yields me an error: `‘hashWithSalt’ is not a (visible) method of class ‘Hashable’`.
has anyone had a similar experience? am I doing something wrong here?

**Comment by phadej** [comment]
Have you imported

```haskell
import Data.Hashable (Hashable)
```

or 

```haskell
import Data.Hashable (Hashable (..))
```

former does not work, if you want to define instances.

**Comment by tycho01** [comment]
I'm silly. Thank you! :sweat_smile:
