### ISSUE TITLE
Add support for ghc-bignum

### ISSUE THREAD

**Issue by phadej** [tibbe/hashable#188]
Can we use `ghc-bignum` directly on GHC-9.0+

EDIT: example in `integer-logarithms` https://github.com/Bodigrim/integer-logarithms/blob/1e64456f35a2d82012a477a70cd8216312422ba0/integer-logarithms.cabal#L69-L81

**Comment by hvr** [comment]
> Can we use `ghc-bignum` directly on GHC-9.0+?

Ok, but what's the benefit if we still have the cheap integer-gmp
compat-layer around (which I suspect will linger around in our
install-plans for years to come) which allows to avoid replicating those
conditionals everywhere in consumers? ;-)

**Comment by phadej** [comment]
> Ok, but what's the benefit if we still have 

The same as having dependency on `void` or `nats` as conditional on older GHCs.
