### ISSUE TITLE
Failure under ghci/TH on 64bit Win7

### ISSUE THREAD

**Issue by ndmitchell** [tibbe/hashable#46]
A user has been been trying to install uniplate via Cygwin on Windows 7x64 running ghc 7.6.1, with Cabal 1.16.0.2. The compilation of Uniplate is failing related to " __imp_CryptAcquireContextA", with the error:

    ghc.exe: unable to load package `hashable-1.2.0.2'
    ghc.exe: C:\Program Files\Haskell\hashable-1.2.0.2\ghc-7.6.1\HShashable-1.2.0.2.o: unknown symbol `__imp_CryptAcquireContextA'

I advised the user downgrade to hashable-1.1 which worked.

**Comment by RyanGlScott** [comment]
Both GHC Trac 7097 and 7134 have been fixed as of GHC 7.8, so AFAICT, this bug has been fixed?

**Comment by tibbe** [comment]
Lets assume so. Feel free to open if it resurfaces.
