### ISSUE TITLE
Hashing for lists-of-lists and other things is semi-broken.

### ISSUE THREAD

**Issue by neongreen** [tibbe/hashable#74]
Currently structures containing lists are treated as if they were all concatenated: `hash ["abc"]` == `hash ["a","bc"]` == `hash ("ab", "c")` == `hash "abc"`. That is, hashable completely ignores the structure. Is it deliberate?

I think that in some cituations it might be a serious flaw — for instance, storing all partitions of a list (they would all have one hash).

**Comment by jberryman** [comment]
If anyone's interested I've released a rewrite of hashable called [`hashabler`](https://github.com/jberryman/hashabler) which concerns itself with this issue.

**Comment by phadej** [comment]
With `1.2.4.0` on my machine:
```hs
 Data.Hashable > (hash ["abc"], hash ["a","bc"], hash ("ab", "
(770288776435754308,-3254706873997758045,779577897349174717,-2835585523591699257)
```

This can be closed.

**Comment by tibbe** [comment]
Thanks for verifying!
