### ISSUE TITLE
cabal install fails with bytestring-0.9

### ISSUE THREAD

**Issue by wferi** [tibbe/hashable#86]
Because the preprocessor [does not understand negation](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/cpp/If.html#If), so this test in [`Data/Hashable/Class.hs`](https://github.com/tibbe/hashable/blob/master/Data/Hashable/Class.hs#L82) is always false, and `Data.ByteString.Lazy.Internal` does not get imported:
```
#if !MIN_VERSION_bytestring(0,10,0)
import qualified Data.ByteString.Lazy.Internal as BL -- foldlChunks
#endif
```
I recommend using
```
#if MIN_VERSION_bytestring(0,10,0)
#else
import qualified Data.ByteString.Lazy.Internal as BL -- foldlChunks
#endif
```
instead.

**Comment by hvr** [comment]
that seems very strange to me; using the logical negation operator is quite common in CPP conditionals

**Comment by tibbe** [comment]
That seems odd to me too. Can you tell GHC to dump the preprocessed output so we can see what it looks like?

**Comment by wferi** [comment]
Probably, but please tell me how to do that...

**Comment by hvr** [comment]
would

```
#if !(MIN_VERSION_bytestring(0,10,0))
```

have worked? if so, what's the contents of the `cabal_macros.h` file generated by cabal?

**Comment by wferi** [comment]
Yes, the parenthesized version actually works! I wonder why my previous tests blamed the negation...

**Comment by tibbe** [comment]
I believe cabal_macros.h generated by older cabal was missing some
parentheses.

**Comment by wferi** [comment]
From my `cabal_macros.h`:
```
/* package bytestring-0.9.1.5 */
#define MIN_VERSION_bytestring(major1,major2,minor) \
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 1
```
Have to transport the kids now, see you later!

**Comment by tibbe** [comment]
Looks like an old cabal then. That whole expression should have been
surrounded with (). As a workaround we can add the parens to hashable.

**Comment by wferi** [comment]
Yes, it's cabal 0.8 (Debian oldstable). Upgrading cabal is also problematic. Said workaround in hashable would help me, but other necessary packages also pose problems, so I may eventually give up this GHC 6.12 environment anyway... :(

**Comment by hvr** [comment]
@tibbe btw, if you don't want to workaround this, just set `cabal-version >=1.10` in future releases' `hashable.cabal`
