### ISSUE TITLE
Fails to build with GHC 7.10.1 from the hvr ppa

### ISSUE THREAD

**Issue by ndmitchell** [tibbe/hashable#89]
Given the @hvr PPA as used in Travis buildbot testing, I get the error:

    Data/Hashable/Class.hs:456:14:
        Constructor ‘TypeRep’ should have 4 arguments, but has been given 3
        In the pattern: TypeRep (Fingerprint x _) _ _
        In an equation for ‘hashTypeRep’:
            hashTypeRep (TypeRep (Fingerprint x _) _ _) = fromIntegral x

This is either an error with the @hvr PPA, or a real error that is going to start occurring with GHC 7.10.1.

**Comment by tibbe** [comment]
See #88.

**Comment by ndmitchell** [comment]
Thanks! Any chance of a new release containing this patch? I can't get my packages GHC 7.10 ready without it.

**Comment by hvr** [comment]
@tibbe btw, we'll have to retrofit a couple of `< base 4.8` constraints to existing `hashable` releases affected by this...

**Comment by tibbe** [comment]
@hvr Yeah, I know. There's a trade-off to be made between try to get ready before a GHC release (when things can still change) and after (where others will be waiting for you to update your code.)

**Comment by tibbe** [comment]
I'm almost ready to release this but the build fails because one of my (test) dependencies has a missing upper bound on base (https://travis-ci.org/tibbe/hashable/jobs/54524854):

```
Preprocessing library ansi-wl-pprint-0.6.7.1...
[1 of 1] Compiling Text.PrettyPrint.ANSI.Leijen ( Text/PrettyPrint/ANSI/Leijen.hs, dist/build/Text/PrettyPrint/ANSI/Leijen.o )
Text/PrettyPrint/ANSI/Leijen.hs:312:24:
    Ambiguous occurrence ‘<$>’
    It could refer to either ‘Text.PrettyPrint.ANSI.Leijen.<$>’,
                             defined at Text/PrettyPrint/ANSI/Leijen.hs:372:3
                          or ‘Prelude.<$>’,
                             imported from ‘Prelude’ at Text/PrettyPrint/ANSI/Leijen.hs:76:8-35
                             (and originally defined in ‘Data.Functor’)
```

I'll see if I can work around that so I can at least sanity check the release before making it.

**Comment by tibbe** [comment]
Fixed and released as 1.2.3.2.

**Comment by ndmitchell** [comment]
Thanks for the release. One of my packages is suffering from exactly the same build failure with ansi-wp-pprint :(

**Comment by hvr** [comment]
@ndmitchell just for the record: https://github.com/batterseapower/ansi-wl-pprint/pull/11

**Comment by hvr** [comment]
@tibbe btw, do you want me to batch-edit `base < 4.8` into those `hashable` releases that will break with GHC 7.10.1?

**Comment by tibbe** [comment]
Sure.
