### ISSUE TITLE
build of hashable-1.2.3.2 fails with integer-simple

### ISSUE THREAD

**Issue by quyse** [tibbe/hashable#90]
Build of hashable-1.2.3.2 fails in integer-simple configuration (i.e. with -f-integer-gmp) with the following error:
```
Data\Hashable\Class.hs:269:0:
     error: missing binary operator before token "("
```
Looks like the problem is that MIN_VERSION_integer_gmp macro is not defined. Reverting changes from 6a4437d8a6d10713c61fa21d7e7797d96177f7b9 fixes the problem.

**Comment by hvr** [comment]
Yeah, `MIN_VERSION_xxx()` is only defined if the the respective `xxx` package is actually in scope for the current Cabal package being built. And `integer-gmp` and `integer-simple` are mutually exclusive packages, you can't have both in scope at the same time.

**Comment by quyse** [comment]
Yes, I have only integer-simple for this test, not both. Sorry if I didn't make myself clear, indeed I meant the missing `#ifdef VERSION_integer_gmp`, as you already pointed out in your line note to Class.hs. Thanks!

**Comment by hvr** [comment]
@quyse as you have integer-simple at your disposal for testing... would you mind preparing a pull-request with the missing `#ifdef` added?

**Comment by quyse** [comment]
@hvr Yes, I can do that. I'm at work right now, will try to look into it at the end of the day.
